name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    # Skip CI if 'skip ci' is contained in latest commit message
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    steps:
    
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybind11
        python setup.py install
    
    - name: Test with pytest
      run: |
        python setup.py test
    
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests

    - name: Build documentation
      run: |
        pip install sphinx sphinx_rtd_theme nbsphinx ipython jupyter
	cd docs
	make html

    - name: Commit documentation changes to gh-pages
      run: |
        git clone https://github.com/Hekstra-Lab/reciprocalspaceship.git --branch gh-pages --single-branch gh-pages
        cd gh-pages
        git rm -r .
        git checkout HEAD -- .gitignore README.md .nojekyll
        cp -r ../_build/html/* .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Upload documentation from latest commit" -a || true

    - name: Push documentation changes to gh-pages
      run: |
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}