name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    # Skip CI if 'skip ci' is contained in latest commit message
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    steps:
    
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybind11
        python setup.py install
    
    - name: Test with pytest
      run: |
        python setup.py test
    
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests

